### ISSUE TITLE
test.pl fails

### ISSUE THREAD

**Issue by eserte** [srchulo/DigitalOcean#10]
See http://www.cpantesters.org/cpan/report/3a58ad7e-e79f-11e5-8cfc-deeba2d85be2 for a sample fail report. Probably all fails visible at http://matrix.cpantesters.org/?dist=DigitalOcean%200.15.3 are caused by this problem.

**Comment by marghidanu** [comment]
Yeah, I've tried to install it via cpanminus and it fails.

**Comment by srchulo** [comment]
I've deleted this and will try to push out the new version to CPAN later tonight. Thanks.
