### ISSUE TITLE
Wait on create_droplet

### ISSUE THREAD

**Issue by Davis-A** [srchulo/DigitalOcean#14]
Hi,

Is there a way to call create_droplet that doesn't return until the droplet creation is complete?  

````
my $droplet = $do->create_droplet(
    name => 'adavis-testrunnerr',
    region => "sfo2",
    size => "s-4vcpu-8gb",
    image => $image->id,
    ssh_keys => [ $ssh_key ],
    wait_on_event => 1,
);
````

I've got this but it returns before it even has an IP address let alone is already up.  So I'm having to poll DO till it has provisioned an ip.  

````
do {
  say "sleep count: " . $count;
  sleep(1);
  $count = $count + 1;
  $droplet =  $do->droplet($droplet->id);
} until($droplet->{networks}->{v4}->[0]->{ip_address} || $count > 120);
````

And at this stage the droplet isn't up, it's still being provisioned.  Is there a way to see when creation is no longer in progress?  I'm trying to avoid having to poll the actions url till it is no longer 'in-progress'

**Comment by srchulo** [comment]
Ah, from looking at the code, it looks like I forgot to update the examples to `wait_on_action`:

https://github.com/srchulo/DigitalOcean/blob/master/lib/DigitalOcean.pm#L290

Could you try changing it to this?

```
my $droplet = $do->create_droplet(
    name => 'adavis-testrunnerr',
    region => "sfo2",
    size => "s-4vcpu-8gb",
    image => $image->id,
    ssh_keys => [ $ssh_key ],
    wait_on_action => 1,
);
```

**Comment by Davis-A** [comment]
Hi,

Apologies for the late reply.

This is ... almost perfect!  Without digging in I'm assuming the library polls the actions url then returns but doesn't get any updated data.  Which has left me with this
````
my $droplet = $do->create_droplet(
    name => 'adavis-testrunnerr',
    region => "sfo2",
    size => "s-4vcpu-8gb",
    image => $image->id,
    ssh_keys => [ $ssh_key ],
    wait_on_action => 1,
);
$droplet = $do->droplet($droplet->id);
````

Which is a fantastic improvement.  Thank you so much :)
